### ISSUE TITLE
Add social icons for fellows

### ISSUE THREAD

**Issue by marcnjaramillo** [MLH-Fellowship/prep-portfolio-22.AUG.PREP.2#11]
At the moment, it only displays the fellow name and location. To help people network, we should add social icons to each of the fellow cards.

![Screenshot 2021-09-30 at 14 24 40](https://user-images.githubusercontent.com/34094921/135463524-d5ddd708-920c-4fc0-ba87-02ca80186d9e.png)
- [x] Add LinkedIn icons to the card
- [x] Add Twitter icons to the card
- [x] Add Resume icons to the card
- [x] Add GitHub icons to the card

**Comment by wzy0766** [comment]
I would like to work on this issue. @marcnjaramillo

**Comment by ahmedsaed** [comment]
I think you guys need to close the issue since it's merged successfully

**Comment by meobilivang** [comment]
@Ahmedsaed Thanks for the notice 🙇 Closing issue

**Comment by meobilivang** [comment]
PR resolved the issue: https://github.com/MLH-Fellowship/prep-portfolio-22.AUG.PREP.2/pull/22
