### ISSUE TITLE
Add the pod!

### ISSUE THREAD

**Issue by marcnjaramillo** [MLH-Fellowship/prep-portfolio-22.AUG.PREP.2#13]
Currently, then repository has members of the MLH team on it, but you should replace them with members of the pod.

You can update information in `_data/fellows.yml`

You should work on:
- [x] Replacing the images
- [x] Update the names and locations of each fellow
- [x] #16

**Comment by nightknighto** [comment]
What exactly to update inside the `_config.yml`?
