### ISSUE TITLE
Replace the MLH Fellowship logo with the MLH Prep logo

### ISSUE THREAD

**Issue by marcnjaramillo** [MLH-Fellowship/prep-portfolio-22.AUG.PREP.2#5]
![Screenshot 2021-09-30 at 18 38 57](https://user-images.githubusercontent.com/34094921/135504106-3f0aacc8-4155-463e-ae81-9433ad10ea13.png)

When you go to the project page, it shows the MLH Fellowship logo at the top. It would be great to replace this with the Prep logo and make sure that's used throughout the website!

**Comment by nightknighto** [comment]
That seems to be already fixed:
![image](https://user-images.githubusercontent.com/52013393/182416089-f7a496ea-fd86-424a-a130-8d55b0485f56.png)


Edit: Ok I found it now when I opened one of the cards.
